language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install .[tests]
  - npm install
script:
  - ./scripts/tests.sh
  - ./scripts/flake8.sh
  - ./scripts/pylint.sh
  - ./scripts/jscpd.sh
